### ISSUE TITLE
test for webP support

### ISSUE THREAD

**Issue by jimmywarting** [antimatter15/weppy#3]
Just made this test myself thought i would suggest it
    webpSupport = /webp/.test(document.createElement('canvas').toDataURL("image/webp"));

**Comment by antimatter15** [comment]
It's possible for a browser to have a WebP decoder without necessarily having a WebP encoder (for canvas). The project already has a somewhat more verbose feature test https://github.com/antimatter15/weppy/blob/master/weppy.js#L287 which involves decoding a data url and checking the sizes (to ensure that the decoder works).
