### ISSUE TITLE
webp not supported in Firefox canvas.toDataURL

### ISSUE THREAD

**Issue by manuq** [antimatter15/weppy#4]
Hi,

Is weppy able to fix this? In Firefox:

```
var c = document.createElement('canvas')
c.toDataURL('image/webp')
"data:image/png;base64,....."
```

If I try the same in Chrome, I get a string "data:image/webp;base64,.....".

**Comment by antimatter15** [comment]
No weppy can only do decoding not encoding because it's not a real  implementation of vp8.

**Comment by manuq** [comment]
OK, thanks.
